[tool.flake8]
ignore = ["C901", "D100", "D101", "D102", "D103", "W503", "W504"]
exclude = ['.eggs', '.git', '.tox', '.venv', '.build', 'build', 'report', 'docs']
max-line-length = 99
max-complexity = 10
extend-ignore = ["E203", "E704"]

[tool.black]
line-length = 99
exclude = '''
/(
    | .eggs
    | .git
    | .tox
    | .venv
    | .build
    | build
    | report
    | docs
)/
'''

[tool.isort]
profile = "black"
skip_glob = [
    ".eggs",
    ".git",
    ".tox",
    ".venv",
    ".build",
    "build",
    "report",
    "docs"
]

[tool.pylint]
max-line-length = 99
load-plugins = "pylint.extensions.docparams"
ignore-paths = [
    ".eggs",
    ".git",
    ".tox",
    ".venv",
    ".build",
    "build",
    "report",
    "tests",
    "docs"
]
no-docstring-rgx = "__.*__"
default-docstring-type = "sphinx"
accept-no-param-doc = false
accept-no-raise-doc = false
accept-no-return-doc = false
accept-no-yields-doc = false
disable = [
    "import-error",
    "consider-using-f-string",
    "missing-type-doc",
]

[tool.mypy]
warn_unused_ignores = true
warn_unused_configs = true
warn_unreachable = true
disallow_untyped_defs = false
ignore_missing_imports = true
exclude = [
    ".eggs",
    ".git",
    ".tox",
    ".venv",
    ".build",
    "build",
    "lib",
    "report",
    "tests",
    "docs"
]

[tool.codespell]
skip = ".eggs,.tox,.git,.venv,venv,build,.build,lib,report,docs"
quiet-level = 3
check-filenames = true
ignore-words-list = "assertIn"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::RuntimeWarning",
]
