name: Check workflow running linter, unit and functional tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - '**.rst'

concurrency:
      # We do not want to run multiple jobs for single PR.
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: true

jobs:
  lint-unit:
    name: Lint checkers and Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Run lint checkers
      run: tox -e lint
    - name: Run unit tests
      run: tox -e unit
